version: '3'
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=twitter_db
    ports:
      - '5433:5432'